{ name : (Text)
, retries : (Optional Natural)
, url : (Optional (Text))
, host : (Optional (Text))
, port : (Optional (Text))
, protocol : (Optional (Text))
, connection_timeout : (Optional Natural)
, write_timeout : (Optional Natural)
, tags : (Optional (List Text))
}
